# Generated by Django 2.2.2 on 2019-06-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190616_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
    ]
